### ISSUE TITLE
Crashes if you encounter a pokemon with no pokeballs, but only ultra balls.

### ISSUE THREAD

**Issue by rhizomatiq** [BoBeR182/Pokemon-Go-Bot-Working-Hack-API#11]
2016-07-27 02:12:11,624 [    pgoapi] [ INFO] Throwing pokeball type: Pokeball
2016-07-27 02:12:11,625 [   pokebot] [ERROR] Main loop has an ERROR, restarting 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "pokebot.py", line 95, in main
    api.main_loop()
  File "/Users/XXXXX/Downloads/a/pgoapi/pgoapi.py", line 502, in main_loop
    while self.catch_near_pokemon():
  File "/Users/XXXXX/Downloads/a/pgoapi/pgoapi.py", line 280, in catch_near_pokemon
    return self.encounter_pokemon(target[0])
  File "/Users/XXXXX/Downloads/a/pgoapi/pgoapi.py", line 421, in encounter_pokemon
    capture_status = catch_attempt['status']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by BoBeR182** [comment]
Should be fixed. I undid the last bad merge.

**Comment by rhizomatiq** [comment]
No i dont think it is. I saw you removed that stuff earlier so I removed it to but no dice. The problem is the bot only works if you have pokeballs and greatballs. On my accounts i only have ultra balls and it literally wont start on any of them until i get myself pokeballs. How can i fix it

Also, does this bot farm pokestops at all?

**Comment by TremendousTurtle** [comment]
This should at least force the bot to farm pokestops until it gets some normal pokeballs.

https://github.com/BoBeR182/Pokemon-Go-Bot-Working-Hack-API/pull/12

**Comment by TremendousTurtle** [comment]
I should note this is the quick fix. I'm working on a better "farming" mode that's smarter and quicker about just running to stops and getting items when you are low.

The code for throwing pokeballs should probably also be updated to not just throw exceptions when a type of pokeball is out as well.

**Comment by rhizomatiq** [comment]
this definitely got it running again thanks bud

**Comment by BoBeR182** [comment]
The maximum amount of items allowed without spending real money is 350 including a camera and incubators, I will run some tests with dummy accounts and update the items in pgoapi.py to better defaults, as most users will want max potions to us against gyms later.

**Comment by rhizomatiq** [comment]
That's fair, good luck and thank you both

**Comment by BoBeR182** [comment]
Updated to not crash if out of balls but use the next tier up.
